### ISSUE TITLE
running cluster

### ISSUE THREAD

**Issue by djvujke** [devgateway/ansible-role-pacemaker#1]
Hi,
I've created my cluster manually. Nothing special.
Then i wanted to test ansible book for it. But when i run it i get this error

TASK: [styopa.pacemaker | Ensure the password for the cluster user] **********\* 
failed: [20cent] => {"failed": true}
msg: this module requires key=value arguments (['name={#', 'pacemaker_user', '#}', 'password={#', 'pacemaker_password', '|', 'password_hash(sha512,', 'ansible_hostname)', '#}'])
failed: [10cent] => {"failed": true}
msg: this module requires key=value arguments (['name={#', 'pacemaker_user', '#}', 'password={#', 'pacemaker_password', '|', 'password_hash(sha512,', 'ansible_hostname)', '#}'])

FATAL: all hosts have already failed -- aborting

And my playbook looks like this
- hosts: mycluster
  roles:
  - styopa.pacemaker
    vars:
    pacemaker_ansible_group: mycluster
    pacemaker_password: Support1209
    pacemaker_cluster_name: 30cent
    pacemaker_properties:
      stonith_enabled: "true"
    pacemaker_resources:
  
  ```
  - id: dns-ip
    type: "ocf:heartbeat:IPaddr2"
    options:
      ip: 16.53.125.50
      cidr_netmask: 8
    op:
      - action: monitor
        options:
          interval: 5s
  ```

Here are the variables
## root@mybook:/etc/ansible/roles/styopa.pacemaker/vars# cat main.yml 

pacemaker_package: pcs
pacemaker_user: hacluster
