### ISSUE TITLE
Error during configure attributes for advanced resource

### ISSUE THREAD

**Issue by lukikawalec** [devgateway/ansible-role-pacemaker#14]
I try to configure advanced resource with meta and I get error "'dict object' has no attribute 'name'". 
Probably the cause is nvpair.name in loop_control.labal. Should be nvpair.key.
https://github.com/devgateway/ansible-role-pacemaker/blob/master/tasks/advanced-resource.yml#L22

**Comment by cu12** [comment]
@lukikawalec this works for me:

```
  - name: Configure NFS resource
    include_role:
      name: pacemaker
      tasks_from: advanced-resource
    vars:
      pcmk_resource:
        type: clone
        id: clo_nfs
        resources:
          p_nfs_server:
            class: lsb
            type: nfs-kernel-server
            meta:
              globally-unique: "false"
              target-role: "Started"
            op:
            - name: monitor
              interval: 10s
              timeout: 30s
```
